---
title: "RDS5_practice"
author: "Tianyu"
date: "2022-10-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### RDS5 practice

```{r librarystuff, include = FALSE}
library(airway)
data(airway, package = "airway")
class(airway)
library(SummarizedExperiment)
```

### get the data that we need

```{r getdata, include = TRUE}
assays(airway)
expression <- assays(airway)[[1]]
head(expression)
nrow(expression)
variances <- apply(expression, 1, var)
expression <- expression[order(variances, decreasing=TRUE)[1:50],]
head(expression)

```

### get data from database and make annotation

```{r annotation, include = TRUE}
library(org.Hs.eg.db)
annotation <- merge(toTable(org.Hs.egSYMBOL), toTable(org.Hs.egENSEMBL2EG))
gene_names <- annotation$symbol[match(rownames(expression), annotation$ensembl_id)]
rownames(expression)[! is.na(gene_names)] <- paste(gene_names[! is.na(gene_names)], 
                                                   rownames(expression)[! is.na(gene_names)], sep = ' / ')
experiment <- data.frame(colData(airway))
head(experiment)

```

### heatmaps

```{r paintheatmaps, include = TRUE}
library(pheatmap)
pheatmap(expression)
pheatmap(expression, scale = 'row', fontsize_row = 4,fontsize_col=12)
expression <- log2(expression + 1)
pheatmap(expression, fontsize_row = 6,fontsize_col=12)
pheatmap(expression, scale='row', annotation_col=experiment, fontsize_row = 5,fontsize_col = 12)
pheatmap(expression, scale='row', annotation_col=experiment[, c("cell", "dex")], fontsize_row = 5,fontsize_col = 12)
#not a improvement, need to fix the ordering in the experiment
experiment <- experiment[with(experiment, order(dex, cell)), ]
expression <- expression[,rownames(experiment)]
#then plot it again
pheatmap(expression, scale='row', annotation_col=experiment[, c("cell", "dex")], annotation_colors = list(dex = c(trt="black",untrt="white"), cell = c('N052611' = 'red', 'N061011' = 'blue', 'N080611' = 'green', 'N61311' = 'yellow')), main = "my beautiful heatmap-TDS5", legend = FALSE, fontsize_row = 5,fontsize_col = 12)
```





